global class CAZ_WS_SActualizacionDatoData {
    public Boolean CAZ_VieneDeWS {get; set;}
    public String CAZ_IdExterno {get; set;}
    public String CAZ_Email {get; set;} 
    public String CAZB_Calle {get; set;}
    public String CAZB_Ciudad {get; set;}
    public String CAZB_CodigoPostal {get; set;}
    public String CAZB_Colonia {get; set;}
    public String CAZB_Estado {get; set;}
    public String CAZB_Municipio {get; set;}
    public String CAZB_No_exterior {get; set;}
    public String CAZB_No_interior {get; set;}
    public String CAZB_Pais {get; set;}
    public String CAZS_Calle {get; set;}
    public String CAZS_Ciudad {get; set;}
    public String CAZS_CodigoPostal {get; set;}
    public String CAZS_Colonia {get; set;}
    public String CAZS_Estado {get; set;}
    public String CAZS_Municipio {get; set;}
    public String CAZS_No_exterior {get; set;}
    public String CAZS_No_interior {get; set;}
    public String CAZS_Pais {get; set;}

    global CAZ_WS_SActualizacionDatoData() {}
}